### ISSUE TITLE
RuntimeWarning (sqrt) + RecurssionError

### ISSUE THREAD

**Issue by blat-blatnik** [marten-de-vries/surfacetracer#1]
So I just downloaded all of the code and dependencies and tried to run. This is the output:

```bash
$ python3 surfacetracer2.py
helpers.py:45: RuntimeWarning: invalid value encountered in sqrt
  return numpy.sqrt(numpy.dot(x, x))
triangles in 2
Traceback (most recent call last):
  File "surfacetracer2.py", line 611, in <module>
    main()
  File "surfacetracer2.py", line 593, in main
    scene = Scene.load_from_json(json_path)
  File "surfacetracer2.py", line 389, in load_from_json
    tree = BSPTree.from_list(surfaces)
  File "surfacetracer2.py", line 197, in from_list
    tree.add(triangle)
  File "surfacetracer2.py", line 232, in add
    self.add(Triangle([a, b, A], triangle.material))
  File "surfacetracer2.py", line 232, in add
    self.add(Triangle([a, b, A], triangle.material))
  File "surfacetracer2.py", line 232, in add
    self.add(Triangle([a, b, A], triangle.material))
  [Previous line repeated 985 more times]
  File "surfacetracer2.py", line 231, in add
    if not numpy.allclose(a, A, EPSILON):
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 2423, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 2534, in isclose
    cond[finite] = within_tol(x[finite], y[finite], atol, rtol)
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 2509, in within_tol
    with errstate(invalid='ignore'):
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 3059, in __enter__
    self.oldstate = seterr(**self.kwargs)
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 2737, in seterr
    old = geterr()
  File "D:\Python37\lib\site-packages\numpy\core\numeric.py", line 2796, in geterr
    maskvalue = umath.geterrobj()[1]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Here is my numpy and python version:

```python
>>> import sys, numpy
>>> print(sys.version)
3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
>>> print(numpy.__version__)
1.16.2
```

Any ideas what could cause this?

**Comment by marten-de-vries** [comment]
This is my setup (which doesn't run into that error):

```python
>>> import sys, numpy
>>> print(sys.version)
3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
>>> print(numpy.__version__)
1.18.4
>>> 
```

64-bit Ubuntu 20.04

Having said that, my guess would be that I made a mistake in the implementation of the BSP tree based on that backtrace. It might try to split up a triangle it has already split. Normally, the `all_close` check mentioned in the backtrace should avoid that, but it might not cover all the cases or the floating point epsilon I chose might be too low. Of course, that's just speculation.
